# Generated by Django 4.2 on 2026-01-16 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Classe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=50)),
                ("filiere", models.CharField(max_length=100)),
                ("departement", models.CharField(max_length=100)),
                ("effectif", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Salle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=50)),
                ("capacite", models.IntegerField()),
                (
                    "type_salle",
                    models.CharField(
                        choices=[("Amphi", "Amphi"), ("TD", "TD"), ("Labo", "Labo")],
                        default="TD",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10)),
                ("nom", models.CharField(max_length=100)),
                (
                    "classe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scheduler.classe",
                    ),
                ),
                (
                    "enseignant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmploiDuTemps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jour", models.CharField(max_length=20)),
                ("plage_horaire", models.CharField(max_length=50)),
                ("date_passage", models.DateField()),
                ("semestre", models.IntegerField(default=1)),
                (
                    "annee_academique",
                    models.CharField(default="2025/2026", max_length=20),
                ),
                (
                    "salle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scheduler.salle",
                    ),
                ),
                (
                    "ue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="scheduler.ue"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Desiderata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jour",
                    models.CharField(
                        choices=[
                            ("Lundi", "Lundi"),
                            ("Mardi", "Mardi"),
                            ("Mercredi", "Mercredi"),
                            ("Jeudi", "Jeudi"),
                            ("Vendredi", "Vendredi"),
                            ("Samedi", "Samedi"),
                        ],
                        max_length=20,
                    ),
                ),
                ("plage_horaire", models.CharField(max_length=50)),
                ("valide", models.BooleanField(default=False)),
                (
                    "enseignant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
